name: Generate functions
on: push
jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - run: printenv | grep '_FUNC'
        env:
          FORMAT_FUNC: ${{ format('{0}, {1}.', 'Hi', 'World' ) }} # 형식 지정
          JOIN_FUNC: ${{ join(github.event.*.html_url, ', ') }} # 쉼표로 결합